import { nanoid } from "nanoid"

/**
 * Represents a node within the graph structure. 
 */
export class Node {
    /**
     * A unique id, generated by nanoid(), used to differentiate this node from others.
     */
    public id: string = nanoid();
    /**
     * The x and y position for this node. 
     */
    public position: { x: number, y: number } = { x: 0, y: 0 };
    /**
     * The width and height for this node. 
     */
    public dimension: { w: number, h: number } = { w: 0, h: 0 };
    /**
     * The text label for this node. 
     */
    public label: string = "";
};

/**
 * Represents a directed edge within the graph structure.
 */
export class Edge {
    /**
     * A unique id, generated by nanoid(), used to differentiate this edge from others.
     */
    public id: string = nanoid();
    /**
     * The id of the node this edge starts from.
     */
    public source: string = "";
    /**
     * The id of the node this edge ends at.
     */
    public target: string = "";
    /**
     * The text label for this edge.
     */
    public label: string = "";
};


/**
 * 
 */
export interface Matrix {
    a: number,
    b: number,
    c: number,
    d: number,
    e: number,
    f: number
};