name: loom

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: |
        npm ci

    - name: Build
      run: |
        npm run build:loom:prod
    
    - name: Test
      run: |
        npm run  test:loom:headless
    
    - name: Build Docs
      run: |
        npm run compodoc:build